travis:
  secure:
    BINSTAR_TOKEN: ims9Lz3dLfsJ+t5m6HHBOfLX/5oJ5UUL+5NCTUJHXtlsHaC3kRd3jA0+NI6U6fSuTyQ5iUC5bAf4G5zzqR0TTYOWFxbJWUeqHRvLpN/Eq73Sh8KLKMZaLQF5N3wxS689X0vyFA6RSLOg9yy0iaSMZJu8UVEEIncvLPWq6UbZZeeCzgciZ9/nkQIYXQWIZYbluZzX3z9rXwTNO4UeCXho18f0LWJcWOA/P66kniAFHEDawnAu/QnUFy5ek1rMxrpBtjJ4+fk6EJi7nQnMXD6EE3TRg7gZLZyANJMMkvwNrp97bAcPdaKTanVwPOYRK/1ge/gWPWVOrPvouKjWAI4ivYeDRy5EJoDfBcv5wOi5gvKiZCgX1ysg1sJxXElCQ1G4grlLvihBuOz3MAV/od6e819uEKkhqGKDZCOFOwcc9JEQ/ZW4csRsil0U/gtk3SCaaQPxDQz/iScKZupcvgfFur8q5DR4exCSLntf5EelT0lxoWKbBCxzceeoyxgulbR4fqWVN8wTSI7O6sjF5OIxiJP7Y5cCtKI8sBofin5pjRJmS8C0aDyQUuWcn+aGC8lf86UwdGbVWcQ/tQRhWJNLz2sZxoaeApj5WsRvbR9yHyG+j1nUNrnuxb3waMwn5y+D875WOXCEe4GuhLAA7zET+ySRL8CNto+Xs7r3EJy4X0w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
